spring.application.name=spring-basics
server.port=8080
com.tek.cors.url=http://localhost:3000
spring.datasource.url=jdbc:mysql://localhost:3306/oms
spring.datasource.username=root
spring.jpa.hibernate.ddl-auto=update
spring.datasource.password=Welcome@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
com.tek.security.jwtSecret=THISISMYVERYLONGJWTSECRETKEYJWTSECRETKEY
com.tek.jwtExpirationMs=100000000